name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prerequisite
      run:
        - git config --global user.name Tester
        - git config --global user.email tester@gmail.com
    - name: Build
      run: cargo build --workspace --tests  
    - name: Test
      run: cargo test --workspace 
    - name: Clippy
      run: cargo clippy --workspace --tests 
    - name: Format
      run: cargo fmt -- --check
