name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --workspace --tests --verbose 
    - name: Test
      run: cargo test --workspace --verbose
    - name: Clippy
      run: cargo clippy --workspace --tests-- verbose
    - name: Format
      run: cargo fmt -- --check
